import Link from "next/link";
import ContactForm from "@/components/contact-form";
import PublicNav from "@/components/public-nav";

const localExamples = [
  { country: "Argentina", flag: "🇦🇷", label: "Buenos Aires", client: "Che, ¿tenés turno para esta semana?", answer: "¡Sí! Te paso los horarios que quedan y agendamos el que te sirva.", note: "Cercano, claro y sin sonar robótico." },
  { country: "Perú", flag: "🇵🇪", label: "Lima", client: "Hola, ¿me pasas info y precios, porfa?", answer: "Claro que sí. Te comparto las opciones y qué incluye cada una.", note: "Respeta la forma local de conversar." },
  { country: "Colombia", flag: "🇨🇴", label: "Medellín", client: "Hola, ¿me regalas información para una cita?", answer: "¡Con gusto! Te cuento cómo funciona y revisamos disponibilidad.", note: "Amable, resolutivo y a tu manera." },
  { country: "México", flag: "🇲🇽", label: "Ciudad de México", client: "¿Me compartes info? Quiero hacerlo ahorita.", answer: "¡Claro! Te explico las opciones y te ayudo a dejar todo listo.", note: "Entiende intención, contexto y urgencia." },
];

export default function Home(){
 return <main>
  <PublicNav/>
  <section className="service-hero shell"><div><p className="eyebrow"><span className="pulse"/>Hecho para atender como atendemos en Latam</p><h1>Tu negocio siempre<br/><em>tiene quién responda.</em></h1><p className="hero-text">Organiza la información de tu negocio y responde por WhatsApp de forma clara, rápida y con el tono que tu gente reconoce.</p><div className="hero-actions"><Link className="button button-primary" href="/login">Crear mi espacio <span>→</span></Link><Link className="text-link" href="/precios">Ver planes y precios <span>↓</span></Link></div><p className="small-trust">Sin contratos largos · Configuración en español · Pensado desde Latinoamérica</p></div><aside className="service-card"><span className="card-label">LUNES, 8:42 A.M. · BOGOTÁ</span><h2>Una buena respuesta puede ser una venta.</h2><div className="service-message">Hola, ¿me regalas información del servicio?</div><div className="service-reply">¡Claro que sí! Te cuento las opciones y revisamos cuál te funciona mejor.</div><div className="service-status"><span>●</span> Atención que suena a tu negocio</div></aside></section>
  <section className="proof shell"><p>ATENCIÓN SIMPLE PARA NEGOCIOS QUE MUEVEN LATINOAMÉRICA</p><div><strong>24/7</strong><span>primera respuesta</span></div><div><strong>1 lugar</strong><span>para tu información</span></div><div><strong>Tu tono</strong><span>en cada conversación</span></div></section>
  <section className="local-section"><div className="shell"><div className="local-heading"><div><p className="eyebrow">El idioma también es contexto</p><h2>La misma IA.<br/><em>Más de tu tierra.</em></h2></div><p>Ayúdame adapta las respuestas al español y a las expresiones que usan tus clientes. Natural, respetuoso y siempre alineado con la voz de tu negocio.</p></div><div className="local-grid">{localExamples.map((example) => <article className="local-card" key={example.country}><div className="local-card-head"><span className="country-flag">{example.flag}</span><div><strong>{example.country}</strong><small>{example.label}</small></div><span className="local-dot">●</span></div><div className="local-bubble local-client">{example.client}</div><div className="local-bubble local-answer">{example.answer}</div><p>{example.note}</p></article>)}</div></div></section>
  <section id="como-funciona" className="how"><div className="shell"><div className="section-intro light"><p className="eyebrow">Así de simple</p><h2>Empieza con lo que ya sabes<br/>de tu negocio.</h2></div><div className="steps"><div><span>1</span><h3>Cuéntanos de tu negocio</h3><p>Sube información, preguntas frecuentes, documentos o una página web.</p></div><div><span>2</span><h3>Revisa tus respuestas</h3><p>Prueba cómo responde antes de compartirlo con tus clientes.</p></div><div><span>3</span><h3>Atiende mejor</h3><p>Conecta tu canal cuando estés listo y conserva el control.</p></div></div></div></section>
  <section id="planes" className="plans shell"><div className="section-intro"><p className="eyebrow">Planes de lanzamiento</p><h2>Simple para empezar.<br/>Acompañado cuando lo necesites.</h2><p>Precios mensuales en pesos colombianos. Incluyen uso razonable del asistente y no tienen permanencia.</p></div><div className="plan-grid"><article className="plan-card"><p className="eyebrow">Light</p><h3>$149.000 <small>COP / mes</small></h3><p>Para negocios que prefieren configurar todo por su cuenta.</p><ul><li>1 usuario</li><li>1 asistente</li><li>Hasta 500 conversaciones/mes</li><li>Artículos, PDFs y enlaces</li><li>Soporte por guías y correo</li></ul><Link className="soft-button" href="/checkout?plan=light">Elegir Light</Link></article><article className="plan-card featured"><span className="plan-badge">RECOMENDADO</span><p className="eyebrow">Full</p><h3>$399.000 <small>COP / mes</small></h3><p>Para negocios que quieren acompañamiento humano y más capacidad.</p><ul><li>Hasta 3 usuarios</li><li>Hasta 3 asistentes</li><li>Hasta 2.000 conversaciones/mes</li><li>Configuración acompañada</li><li>Soporte prioritario por WhatsApp</li></ul><Link className="button button-primary" href="/checkout?plan=full">Elegir Full <span>→</span></Link></article></div><p className="pricing-note">Costos estimados incluidos: infraestructura, almacenamiento y consumo básico del modelo. Si tu uso supera el plan, te contactamos antes de cualquier cobro adicional.</p><Link className="text-link dark-link" href="/precios">Ver comparación completa <span>→</span></Link></section>
  <section id="contacto" className="contact-section"><div className="shell contact-wrap"><div><p className="eyebrow">Hablemos</p><h2>¿Tu negocio ya recibe demasiados mensajes?</h2><p>Cuéntanos qué quieres ordenar o automatizar. Te respondemos personalmente.</p><a className="contact-link" href="mailto:sebastian.espindola.h@gmail.com">sebastian.espindola.h@gmail.com</a><a className="contact-link" href="https://wa.me/573142726805">+57 314 272 6805</a></div><ContactForm/></div></section>
  <footer className="footer shell"><Link className="brand" href="/"><span className="brand-mark">a</span><span>ayúdame</span></Link><span>Atención simple para negocios de Latam.</span><span>© 2026 Ayúdame</span></footer>
 </main>
}